version: '3.7'

services:
  postgre:
    image: postgres:9
    container_name: 'todo-db'
    environment:
      POSTGRES_USER: 'todo-user'
      POSTGRES_PASSWORD: 'todo-password'
      POSTGRES_DB: 'db_todo'
    ports:
      - '5432:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'